def write(image, fout, size=None, cell_size=None):
    fout.write(b'\x1bPq')
    fout.write(b'#1;2;255;0;0')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-')
    fout.write(b'#3;2;0;0;255')
    fout.write(b'#3~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~$')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~$')
    fout.write(b'#2;2;0;255;0')
    fout.write(b'#2??????EEEEEEEEEEEEEE~~~~~~~~~-')
    fout.write(b'#1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~$')
    fout.write(b'\x1b\\')
